### ISSUE TITLE
[BUG]: Small typo in README.md

### ISSUE THREAD

**Issue by zaerl** [snyk-snippets/modern-npm-package#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

That's a small type in `README.md`:

> Install developer dependencies using the following command in your terminal npm i -D mocha **@type/mocha** chai @types/chai ts-node

It should be:

> Install developer dependencies using the following command in your terminal npm i -D mocha **@types/mocha** chai @types/chai ts-node

### Steps To Reproduce

Just check the file 🙂

**Comment by clarkio** [comment]
Good catch! Thanks for bringing this up. It's now fixed in https://github.com/snyk-snippets/modern-npm-package/commit/d886ddbef098fc8254cc6773d3e39d4bd846d5ea
