### ISSUE TITLE
[BUG]: The tutorial on https://snyk.io/blog/best-practices-create-modern-npm-package/ has not working repo link

### ISSUE THREAD

**Issue by rrakso** [snyk-snippets/modern-npm-package#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

There is info on the website https://snyk.io/blog/best-practices-create-modern-npm-package/ to clone this https://github.com/snyk-labs/simple-npm-package.git repo, but such repo doesn't exists, instead this one exists https://github.com/snyk-labs/modern-npm-package.git.

I think that this can be a bug 😉 

### Steps To Reproduce

Try to: `git clone https://github.com/snyk-labs/simple-npm-package.git`

**Comment by clarkio** [comment]
This does exist here: https://github.com/snyk-labs/simple-npm-package. Could you double check you can see it and let me know?

**Comment by fuho** [comment]
@clarkio 
Looks to me like there are two repos in existence:  
 - https://github.com/snyk-snippets/modern-npm-package - **snippets**, _modern_  
 - https://github.com/snyk-labs/simple-npm-package - _labs_, **simple**  

This is a screenshot from the blog post:  **snippets**, **simple**
<img width="838" alt="image" src="https://user-images.githubusercontent.com/539452/225399930-71f85180-c28f-465b-957e-7b477d2b585c.png">

Thanks for the blog post BTW, found it very helpful.

**Comment by clarkio** [comment]
@fuho thanks for your patience on this. I've added the repo under that organization now here: https://github.com/snyk-labs/simple-npm-package

**Comment by clarkio** [comment]
This should be addressed now and closing the issue as a result. If you find there is something still off regarding the links please open a new issue.
